name: $remont

on:
  workflow_dispatch:
  push:
  pull_request:
  schedule:
  - cron: "0 7 * * *"

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    
    - uses: hyoo-ru/mam_build@master2
      with:
        package: 'hyoo/template' #FIXME namespace of this package
        modules: 'app' #FIXME which modules to build, remove line if only on module at the root
    
    - uses: JamesIves/github-pages-deploy-action@4.1.7
      with:
        branch: gh-pages
        folder: remont/market2/-
